In [1]:
import numpy as np

In [2]:
#1. Write a NumPy program to test whether none of the elements of a given array is zero.

arr = np.array([0,1, 2, 3, 4, 5])

arr.all()

False

In [3]:
#2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

arr = np.array([0,1, 2, 3, 4, 5])

arr.any()


True

In [4]:
#3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given
a = np.array([1,2,3,4])
b = np.array([1,2,3,3.99999999999999999999999])


np.allclose(a,b)

True

In [5]:
#4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

a = np.arange(1,31)

a = np.zeros((3,10)).astype(int)
a[-1 , :] = 5

a[:1 , :] = 1
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [6]:
#5. Write a NumPy program to create an array of the integers from 30 to70.

np.arange(30,71).astype(int)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [7]:
#6. Write a NumPy program to create a 3x3 identity matrix
x = np.diag([1,1,1]).astype(int)
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [8]:
#7. Write a NumPy program to generate a random number between 0 and 1
np.random.uniform(0,1)

0.842623873444424

In [9]:
#8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

np.random.randint(0,100,15)

array([51, 76, 95, 46, 73, 70,  3, 67, 68, 27, 70, 30, 97, 78, 62])

In [10]:
#9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values 
#except the first and last.
v = np.arange(15,56)

v[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [11]:
#10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

v = np.random.randint(0,10,5)

v

array([6, 6, 4, 4, 3])

In [12]:
#11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal
#to 1, and inside 0.

y = np.zeros((10,10)).astype(int)
y[0:1 , :] = 1
y[: , 0:1] = 1
y[: , -1] = 1
y[-1, :] = 1

y

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [13]:
#12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,3, 4, 5.
y = np.diag([1,2,3,4,5])
y

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [14]:
#13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main
#diagonal.

m = np.zeros([4,4]).astype(int)
m[0:1,-1] = 1
m[2,-1] = 1
m[3,0] = 1
m[0,1] = 1
m[1,0] = 1
m[1,2] = 1
m[2,1] = 1
m[3,2] = 1
m

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [15]:
#14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) 
#and load it.

a = np.array([1,2,3,4])

b = np.array([5,6,7,8])


h=np.savez("AB",x=a, y=b)
h=np.load("AB.npz")

h['x']

array([1, 2, 3, 4])

In [16]:
#15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.
#Select
np.random.seed(4)
np.random.randint(1,1000,40)



array([123, 175, 440, 710, 898, 361, 600, 457, 819, 394,  59, 765, 872,
       110, 607, 824, 952, 314, 873, 677, 947,  45, 295, 127, 565, 388,
         1, 184, 534, 150, 714, 423, 510, 487,  57, 707, 175, 374,  31,
       649])

In [17]:
#16. Write a NumPy program to extract all numbers from a given array which are less and greater than a
#specified number.

x = np.arange(1,10)
y = 4
x[x>y]


array([5, 6, 7, 8, 9])

In [18]:
z=7
x[x<z]

array([1, 2, 3, 4, 5, 6])